import { builtinModules } from "node:module";
import esbuild from "esbuild";

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */`;

const isProd = process.argv.includes("--production");

const config = {
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	outfile: "main.js",
	external: [
		"obsidian",
		"electron",
		...builtinModules
	],
	format: "cjs",
	platform: "node",
	target: "es2018",
	sourcemap: isProd ? false : "inline",
	minify: isProd,
	logLevel: "info",
};

async function build() {
	if (isProd) {
		await esbuild.build(config);
	} else {
		const ctx = await esbuild.context(config);
		await ctx.watch();
	}
}

build().catch(() => process.exit(1));